# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
