# Generated by Django 3.0.4 on 2020-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders', '0003_auto_20200404_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaderfailure',
            name='request',
        ),
        migrations.RemoveField(
            model_name='loaderfailure',
            name='response',
        ),
        migrations.DeleteModel(
            name='RequestData',
        ),
        migrations.DeleteModel(
            name='ResponseData',
        ),
    ]
