# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
