# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_radio_active'),
    ]

    operations = [
        migrations.RenameField('Play', 'artist', 'artist_name'),
    ]
