# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def populate_derived_data(apps, schema_editor):
    Radio = apps.get_model("radio", "Radio")

    for radio in Radio.objects.all():
        plays = radio.play_set.order_by('timestamp')
        radio.first_play = plays.first()
        radio.last_play = plays.last()
        radio.play_count = plays.count()
        radio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_rename_play_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='first_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='radio.Play'),
        ),
        migrations.AddField(
            model_name='radio',
            name='last_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='radio.Play'),
        ),
        migrations.AddField(
            model_name='radio',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_derived_data, migrations.RunPython.noop),
    ]
