# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('radio', '0006_auto_20171031_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Artist'),
        ),
    ]
