# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
