# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models

"""
Replaces default indices generated by db_index=True with custom indices using
the iunaccent function.
"""

create_artist_index = """
    CREATE INDEX idx__radio_play___upper_iunaccent_artist_name
    ON radio_play(upper(iunaccent(artist_name)));
"""

create_title_index = """
    CREATE INDEX idx__radio_play__upper_iunaccent_title
    ON radio_play(upper(iunaccent(title)));
"""

drop_artist_index = """
    DROP INDEX idx__radio_play___upper_iunaccent_artist_name
"""

drop_title_index = """
    DROP INDEX idx__radio_play__upper_iunaccent_title
"""


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_auto_20180903_1306'),
        ('music', '0002_indices'),
    ]

    operations = [
        migrations.RunSQL(create_artist_index, drop_artist_index),
        migrations.RunSQL(create_title_index, drop_title_index)
    ]
