# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_better_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
