# Generated by Django 3.1.14 on 2023-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_auto_20190118_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
