# Generated by Django 5.1 on 2024-08-19 07:34

import django.db.models.functions.text
import radioscraper.postgres.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_radio_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='title_search',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.text.Lower(radioscraper.postgres.lookups.ImmutableUnaccent('title')), output_field=models.CharField(max_length=255)),
        ),
    ]
