# Generated by Django 4.2.20 on 2025-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_radio_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='load',
            field=models.BooleanField(default=True, help_text='Run loaders for this radio'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='offline',
            field=models.BooleanField(default=False, help_text='Show as offline in the UI'),
        ),
    ]
